export const StatusType = {
  SUCCESS: 'SUCCESS',
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
} as const;
